### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by APT-ZERO** [dkxce/SignificatePE#1]
Hi,
Thank you for this great project

Could you please add options to
- Disable Timestamp
- Ignore certificate expire time (to use an expired certificate)

And also option to create a pfx certificate without any gui window or a long process

Thank you.

**Comment by dkxce** [comment]
- You can Disable Timestamp in any version, just print NO_TIMESTAMP into Time Server field;
- To Ignore certificate expire time you can use Release rls4 and Menu Item `Sign retroactively`;
- To create a pfx certificate use MakeCert.exe (https://learn.microsoft.com/en-us/windows-hardware/drivers/devtest/makecert), XCA (https://github.com/chris2511/xca/) or Special Menu Tree;
